# Recheck this file when using this template
stages:
  - build
  - deploy-production

variables:
  VARIABLE_DATA: Gitlab-CI-YAML

build:
  stage: build
  image: docker:20-dind
  services:
    - name: docker:20-dind
      alias: docker
      command: ['--tls=false']
  variables:
    DEPLOY_TAG: 'latest'
    DOCKER_DRIVER: overlay
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_TLS_CERTDIR: ''
  tags:
    - docker
  before_script:
    # login to gitlab registry
    - echo $FOLXCODE_PERSONAL_TOKEN | docker login --username "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  rules:
    - if: $CI_COMMIT_REF_NAME == 'main'
      variables:
        DEPLOY_TAG: 'latest'
      when: manual
    - if: $CI_COMMIT_REF_NAME == 'development'
      variables:
        DEPLOY_TAG: 'latest'
      when: manual
    - if: $CI_COMMIT_REF_NAME != 'main' && $CI_COMMIT_REF_NAME != 'development'
      when: never
  script:
    # build and tag docker image
    - docker build -t $CI_REGISTRY_IMAGE:$DEPLOY_TAG .
    # publish finished image
    - docker push $CI_REGISTRY_IMAGE:$DEPLOY_TAG
  after_script:
    - docker logout

deploy-production:
  only:
    - development
    - main
  stage: deploy-production
  when: on_success
  variables:
    DEPLOY_TAG: 'latest'
  tags:
    - deployment
  before_script:
    # install ssh package and add private key to .ssh
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$FOLXCODE_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $FC_DAVION_SERVER_ADDRESS >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    # connect to server
    - >
      ssh $SERVER_USERNAME@$FC_DAVION_SERVER_ADDRESS
      "cd /home/ubuntu/gitlab/fc-davion-server-docker;
       echo $FOLXCODE_PERSONAL_TOKEN | sudo docker login --username "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY;
       sudo docker pull $CI_REGISTRY_IMAGE:$DEPLOY_TAG;
       sudo docker-compose -f docker-compose.yaml -f apps/example/docker-compose.yaml up -d --force-recreate example-api;
       exit"
